#!/usr/bin/env bash

bun run /Users/rohirikman/.gemini/antigravity/skills/Art/Tools/Generate.ts \
  --model nano-banana-pro \
  --prompt "Nano Banana style digital illustration. Cyberpunk retrofuturism. Near-black background (#0D0D0D). Bold flat colors, hard neon edges, zero gradients. No text in image. Split horizontal composition — left half and right half. LEFT HALF (the before — chaotic, fragmented): A vertical pile of disconnected elements: small script icons (document with bracket, dim gray), scattered clock/cron icons (amber), disconnected cloud service icons (each a different shape — storage blob, database cylinder, lambda function — in varied muted colors), arrows going in different directions, no clear path. The composition is messy, items overlapping and disorganized. Colors muted: gray, dim amber, desaturated blue. RIGHT HALF (the after — clean, organized): A single monolithic infrastructure structure — a vertical server rack silhouette in dark steel, solid and geometric. On top: three glowing container nodes (hexagonal, in purple/cyan/amber). Rising from the center: a brain-like workflow hub in deep purple with geometric circuit traces, pulsing with clean neon lines that connect to all containers below. Everything connected, intentional, hierarchical. Colors vivid: deep purple (#4A148C) for n8n hub, electric cyan for container connections, amber for server warmth. A thin neon-cyan horizontal dividing line separates left and right — the transformation moment. Color palette: near-black background, left side in dim muted gray/amber with desaturated cloud icons, right side in deep purple/cyan/amber neon, server rack in dark steel. The contrast between chaotic left and structured right is the point. Subjects fill the full frame. Minimal." \
  --size 2K \
  --aspect-ratio 16:9 \
  --thumbnail \
  --output ~/Downloads/robot-army-personal-lab.png

bun run /Users/rohirikman/.gemini/antigravity/skills/Art/Tools/Generate.ts \
  --model nano-banana-pro \
  --prompt "Nano Banana style digital illustration. Cyberpunk retrofuturism. Near-black background (#0D0D0D). Bold flat colors, hard neon edges, zero gradients. No text in image. Vertical layered architecture composition — four distinct horizontal bands stacked top to bottom: TOP BAND (edge layer): A wide geometric shield — Azure WAF rendered as a bold hexagonal frame, electric blue with cyan circuit-trace details inside. From its edges, thin neon-white lines branch downward like rays, suggesting traffic entering from above. SECOND BAND (compute layer): A clean server rack silhouette — vertical, geometric, dark steel with amber indicator lights. Solid, grounded. THIRD BAND (network layer): Azure DNS zone — a floating geometric grid of small nodes (dots in a clean pattern), cool cyan, slightly transparent. BOTTOM BAND (monitoring layer): Azure Monitor dashboard — a flat rectangular frame in dark steel with three small chart/line icons inside, warm amber for metrics. Four thin neon-cyan horizontal lines separate the bands, making each layer visually distinct. Each layer labeled implicitly: shield = WAF, rack = compute, grid = DNS, dashboard = monitoring. Color palette: near-black background, WAF shield in electric blue with cyan traces, server rack in dark steel with amber lights, DNS grid in cool cyan, monitoring dashboard in dark steel with amber charts, divider lines in neon-cyan. Clean, technical, organized. Subjects fill the full frame. Minimal. Precise." \
  --size 2K \
  --aspect-ratio 16:9 \
  --thumbnail \
  --output ~/Downloads/new-environment-setup.png

bun run /Users/rohirikman/.gemini/antigravity/skills/Art/Tools/Generate.ts \
  --model nano-banana-pro \
  --prompt "Nano Banana style digital illustration. Cyberpunk retrofuturism. Near-black background (#0D0D0D). Bold flat colors, hard neon edges, zero gradients. No text in image. Center composition: A vertical stack of five interconnected geometric layer blocks — stacked like building floors, ascending from bottom to top: LAYER 1 (bottom, foundation): Identity — a large hexagonal node, warm amber, with a geometric ID badge icon inside. Glowing edges, solid base. LAYER 2: Endpoints — a rectangular block, electric blue, with a small shield-plus-laptop icon inside. Connected to Layer 1 by a vertical neon-cyan line. LAYER 3: Network — a pentagonal block, neon green, with a WiFi/signal icon inside. Connected to Layer 2 by a vertical neon-cyan line. LAYER 4: Cloud — a diamond-shaped block, soft magenta, with a cloud outline icon inside. Connected to Layer 3 by a vertical neon-cyan line. LAYER 5 (top, apex): Monitoring — a small octagonal block, cold cyan, with a chart/gear icon inside. Connected to Layer 4 by a vertical neon-cyan line. Surrounding the stack on left and right: thin neon-cyan lines suggest the full organizational scope. Below the stack: a faint base platform in dim gray, representing legacy infrastructure being replaced. Above: a small glowing shield icon in bright neon-green, representing the overall Zero Trust outcome. Color palette: near-black background, identity layer in warm amber, endpoint layer in electric blue, network layer in neon green, cloud layer in soft magenta, monitoring layer in cold cyan, connecting lines in neon-cyan, legacy base in dim gray, outcome shield in neon-green. Each layer enables the next. Subjects fill the full frame. Minimal." \
  --size 2K \
  --aspect-ratio 16:9 \
  --thumbnail \
  --output ~/Downloads/zero-trust-program-energy-sector.png

bun run /Users/rohirikman/.gemini/antigravity/skills/Art/Tools/Generate.ts \
  --model nano-banana-pro \
  --prompt "Nano Banana style digital illustration. Cyberpunk retrofuturism. Near-black background (#0D0D0D). Bold flat colors, hard neon edges, zero gradients. No text in image. Horizontal pipeline composition — a clean central flow line running left to right, with three major phase nodes along it: PHASE 1 (left): Onboarding — a large hexagonal node, neon green, with a small person-plus-plus icon inside (geometric person with a +). Above it: small icons floating — email, laptop, Slack bubble — the things being provisioned. Connected to pipeline by a thin neon-cyan line. PHASE 2 (center): Role Changes — a medium-sized octagonal node, electric blue, with a gear-arrow icon inside. Above it: small icons — department swap arrows, manager change symbols — in varied neon colors. PHASE 3 (right): Offboarding — a small pentagonal node, deep red (serious cold red), with a broken chain link icon inside. Above it: small icons — a lock closing, a folder archiving, a red X on a user icon — the deprovisioning actions. The pipeline line connects all three phases: bright neon-cyan from Phase 1 to Phase 2, bright neon-cyan from Phase 2 to Phase 3. Small data packets (small rectangles in varied colors) flow along the line left to right. Below the pipeline: a small n8n workflow icon (geometric brain-circuit node in deep purple) — the automation brain orchestrating the pipeline. Thin purple lines connect from it to each of the three phase nodes. Color palette: near-black background, onboarding node in neon green, role-change node in electric blue, offboarding node in serious deep red, pipeline in neon-cyan, n8n brain in deep purple (#4A148C), data packets in varied neon. The three phases distinct but connected — a lifecycle, not three separate events. Subjects fill the full frame. Minimal. Clean flow." \
  --size 2K \
  --aspect-ratio 16:9 \
  --thumbnail \
  --output ~/Downloads/hr-lifecycle-automation.png
