
services:
  fabric-ai:
    container_name: fabric-ai
    build: .
    image: fabric-ai:latest
    ports:
      - "8999:8999"   # Fabric REST API port
      - "5173:5173"   # Fabric Web Interface port
    volumes:
      - fabric_data:/root/.config/fabric
    env_file:
      - .env
    networks:
      - traefik_public
      - n8n_internal
    restart: unless-stopped
    environment:
      - COMPOSE_BAKE=true
    # Traefik labels disabled for local development
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.${FABRIC_AI_SUBDOMAIN}.rule=Host(`${FABRIC_AI_SUBDOMAIN}.${TRAEFIK_DOMAIN}`)"  # Domain name
      - "traefik.http.routers.${FABRIC_AI_SUBDOMAIN}.entrypoints=websecure"  # HTTPS entry point
      - "traefik.http.routers.${FABRIC_AI_SUBDOMAIN}.tls=true"  # Enable TLS/SSL
      - "traefik.http.routers.${FABRIC_AI_SUBDOMAIN}.tls.certresolver=myresolver"  # Let's Encrypt
      - "traefik.http.routers.${FABRIC_AI_SUBDOMAIN}.service=fabric-ai"  # Explicit service link
      - "traefik.docker.network=traefik_public"  # Specify which network Traefik should use
      - "traefik.http.services.fabric-ai.loadbalancer.server.port=8999"  # Internal port
      - "traefik.http.routers.${FABRIC_AI_SUBDOMAIN}.middlewares=secure-headers@file,ip-allowlist@file,rate-limit@file"  # Security
      # HTTP to HTTPS redirect
      - "traefik.http.routers.${FABRIC_AI_SUBDOMAIN}-http.rule=Host(`${FABRIC_AI_SUBDOMAIN}.${TRAEFIK_DOMAIN}`)"  # HTTP rule
      - "traefik.http.routers.${FABRIC_AI_SUBDOMAIN}-http.entrypoints=web"  # HTTP entry point
      - "traefik.http.routers.${FABRIC_AI_SUBDOMAIN}-http.service=${FABRIC_AI_SUBDOMAIN}"  # Explicit service link
      - "traefik.http.routers.${FABRIC_AI_SUBDOMAIN}-http.middlewares=https-redirect@file"  # Redirect to HTTPS

      # Web Interface Labels
      - "traefik.http.routers.${FABRIC_WEB_SUBDOMAIN}.rule=Host(`${FABRIC_WEB_SUBDOMAIN}.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.${FABRIC_WEB_SUBDOMAIN}.entrypoints=websecure"
      - "traefik.http.routers.${FABRIC_WEB_SUBDOMAIN}.tls=true"
      - "traefik.http.routers.${FABRIC_WEB_SUBDOMAIN}.tls.certresolver=myresolver"
      - "traefik.http.routers.${FABRIC_WEB_SUBDOMAIN}.service=fabric-web"  # Explicit service link
      - "traefik.http.services.fabric-web.loadbalancer.server.port=5173"  # Web port!
      - "traefik.http.routers.${FABRIC_WEB_SUBDOMAIN}.middlewares=secure-headers@file,ip-allowlist@file,rate-limit@file"

      # HTTP to HTTPS redirect for Web
      - "traefik.http.routers.${FABRIC_WEB_SUBDOMAIN}-http.rule=Host(`${FABRIC_WEB_SUBDOMAIN}.${TRAEFIK_DOMAIN}`)"
      - "traefik.http.routers.${FABRIC_WEB_SUBDOMAIN}-http.entrypoints=web"
      - "traefik.http.routers.${FABRIC_WEB_SUBDOMAIN}-http.service=fabric-web"  # Explicit service link
      - "traefik.http.routers.${FABRIC_WEB_SUBDOMAIN}-http.middlewares=https-redirect@file"
            
      # Watchtower labels
      - "com.centurylinklabs.watchtower.enable=true"  # Enable auto-updates
      - "com.centurylinklabs.watchtower.cleanup=true"  # Clean up old images



volumes:
  fabric_data:

networks:
  traefik_public:
    external: true 
  n8n_internal:
    external: true
  