name: Content Quality Check

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  markdown-lint:
    runs-on: ubuntu-latest
    name: Markdown Linting
    steps:
      - uses: actions/checkout@v4
      - name: Lint Markdown files
        uses: DavidAnson/markdownlint-cli2-action@v13
        with:
          globs: '**/*.md'

  link-check:
    runs-on: ubuntu-latest
    name: Link Validation
    steps:
      - uses: actions/checkout@v4
      - name: Check links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          config-file: '.github/workflows/link-check-config.json'

  spell-check:
    runs-on: ubuntu-latest
    name: Spell Check
    steps:
      - uses: actions/checkout@v4
      - name: Spell check
        uses: streetsidesoftware/cspell-action@v5
        with:
          files: '**/*.md'
          incremental_files_only: false

